apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-frontend
  template:
    metadata:
      labels:
        app: hackathon-frontend
    spec:
      containers:
      - name: hackathon-frontend
        image: doanh269/hackathon-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-frontend-service
spec:
  selector:
    app: hackathon-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Chuyển sang NodePort thay vì ClusterIP
